'use client';

import type { AIInsightResult } from '@/types';

type Insight = AIInsightResult & { source?: 'ai' | 'mock' };

interface Props {
  insight: Insight | null;
  loading: boolean;
  onGenerate: () => void;
  disabled: boolean;
}

export function AIInsightCard({ insight, loading, onGenerate, disabled }: Props) {
  return (
    <div className="space-y-3 rounded-2xl border border-black/10 p-6 dark:border-white/15">
      <div className="flex items-center justify-between">
        <span className="text-xs font-semibold uppercase tracking-wide text-indigo-500">
          AI insight
        </span>
        <button
          onClick={onGenerate}
          disabled={disabled || loading}
          className="rounded-lg border border-black/15 px-3 py-1.5 text-xs font-semibold transition-colors hover:bg-black/5 disabled:opacity-40 dark:border-white/20 dark:hover:bg-white/10"
        >
          {loading ? 'Analyzing…' : 'Generate AI insight'}
        </button>
      </div>

      {loading && (
        <div className="animate-pulse space-y-2">
          <div className="h-3 w-3/4 rounded bg-gray-300/40" />
          <div className="h-3 w-full rounded bg-gray-300/40" />
          <div className="h-3 w-2/3 rounded bg-gray-300/40" />
        </div>
      )}

      {!loading && insight && (
        <div className="space-y-2">
          <p className="text-sm leading-relaxed">{insight.summary}</p>
          <p className="text-sm leading-relaxed">
            <span className="font-semibold">Recommendation: </span>
            {insight.recommendation}
          </p>
          {insight.source === 'mock' && (
            <p className="text-xs text-gray-400">
              Generated by the built-in rule-based engine (no AI provider configured).
            </p>
          )}
        </div>
      )}

      {!loading && !insight && (
        <p className="text-sm text-gray-400">
          Calculate metrics first, then generate an insight.
        </p>
      )}
    </div>
  );
}
